
compile:
	@tclsh $(bindir)/../../cae_library/simulation/scripts/cmpl_libs.tcl -sim_path /eda/cadence/2023-24/RHELx86/XCELIUM_23.03.007/tools/bin/ -sim_vendor cadence -device lfcpnx -target_path lattice_compiled

#@xrun -sv -compile -64 -define LFCPNX -define LFCPNX_100 -define jd5d00 -f xcelium_lib.f
#fpga_ip_files.f:
#@tclsh make_filelist.tcl