


/*
    Generated by HDL Build
*/
module astep24_20l_top(

    input  wire		sysclk,

    input  wire		cold_resn,
    input  wire		warm_resn,
    output wire		io_aresn,

    output wire		clk_sample,
    output wire		clk_timestamp,


    output wire [2:0]   ext_adc_spi_csn,
    input  wire		ext_adc_spi_miso,
    //output wire		ext_dac_spi_csn,
    output wire		ext_spi_clk,
    output wire		ext_spi_mosi,

    output wire		layer_0_hold,
    input  wire		layer_0_interruptn,
    output wire		layer_0_resn,
    output wire		layer_0_spi_clk,
    output wire		layer_0_spi_csn,
    input  wire [1:0]	layer_0_spi_miso,
    output wire		layer_0_spi_mosi,

    output wire		layer_1_hold,
    input  wire		layer_1_interruptn,
    output wire		layer_1_resn,
    output wire		layer_1_spi_clk,
    output wire		layer_1_spi_csn,
    input  wire [1:0]	layer_1_spi_miso,
    output wire		layer_1_spi_mosi,

    output wire		layer_2_hold,
    input  wire		layer_2_interruptn,
    output wire		layer_2_resn,
    output wire		layer_2_spi_clk,
    output wire		layer_2_spi_csn,
    input  wire [1:0]	layer_2_spi_miso,
    output wire		layer_2_spi_mosi,

    output wire		layer_3_hold,
    input  wire		layer_3_interruptn,
    output wire		layer_3_resn,
    output wire		layer_3_spi_clk,
    output wire		layer_3_spi_csn,
    input  wire [1:0]	layer_3_spi_miso,
    output wire		layer_3_spi_mosi,

    output wire		layer_4_hold,
    input  wire		layer_4_interruptn,
    output wire		layer_4_resn,
    output wire		layer_4_spi_clk,
    output wire		layer_4_spi_csn,
    input  wire [1:0]	layer_4_spi_miso,
    output wire		layer_4_spi_mosi,

    output wire		layer_5_hold,
    input  wire		layer_5_interruptn,
    output wire		layer_5_resn,
    output wire		layer_5_spi_clk,
    output wire		layer_5_spi_csn,
    input  wire [1:0]	layer_5_spi_miso,
    output wire		layer_5_spi_mosi,

    output wire		layer_6_hold,
    input  wire		layer_6_interruptn,
    output wire		layer_6_resn,
    output wire		layer_6_spi_clk,
    output wire		layer_6_spi_csn,
    input  wire [1:0]	layer_6_spi_miso,
    output wire		layer_6_spi_mosi,

    output wire		layer_7_hold,
    input  wire		layer_7_interruptn,
    output wire		layer_7_resn,
    output wire		layer_7_spi_clk,
    output wire		layer_7_spi_csn,
    input  wire [1:0]	layer_7_spi_miso,
    output wire		layer_7_spi_mosi,

    output wire		layer_8_hold,
    input  wire		layer_8_interruptn,
    output wire		layer_8_resn,
    output wire		layer_8_spi_clk,
    output wire		layer_8_spi_csn,
    input  wire [1:0]	layer_8_spi_miso,
    output wire		layer_8_spi_mosi,

    output wire		layer_9_hold,
    input  wire		layer_9_interruptn,
    output wire		layer_9_resn,
    output wire		layer_9_spi_clk,
    output wire		layer_9_spi_csn,
    input  wire [1:0]	layer_9_spi_miso,
    output wire		layer_9_spi_mosi,

    output wire		layer_10_hold,
    input  wire		layer_10_interruptn,
    output wire		layer_10_resn,
    output wire		layer_10_spi_clk,
    output wire		layer_10_spi_csn,
    input  wire [1:0]	layer_10_spi_miso,
    output wire		layer_10_spi_mosi,

    output wire		layer_11_hold,
    input  wire		layer_11_interruptn,
    output wire		layer_11_resn,
    output wire		layer_11_spi_clk,
    output wire		layer_11_spi_csn,
    input  wire [1:0]	layer_11_spi_miso,
    output wire		layer_11_spi_mosi,

    output wire		layer_12_hold,
    input  wire		layer_12_interruptn,
    output wire		layer_12_resn,
    output wire		layer_12_spi_clk,
    output wire		layer_12_spi_csn,
    input  wire [1:0]	layer_12_spi_miso,
    output wire		layer_12_spi_mosi,

    output wire		layer_13_hold,
    input  wire		layer_13_interruptn,
    output wire		layer_13_resn,
    output wire		layer_13_spi_clk,
    output wire		layer_13_spi_csn,
    input  wire [1:0]	layer_13_spi_miso,
    output wire		layer_13_spi_mosi,

    output wire		layer_14_hold,
    input  wire		layer_14_interruptn,
    output wire		layer_14_resn,
    output wire		layer_14_spi_clk,
    output wire		layer_14_spi_csn,
    input  wire [1:0]	layer_14_spi_miso,
    output wire		layer_14_spi_mosi,

    output wire		layer_15_hold,
    input  wire		layer_15_interruptn,
    output wire		layer_15_resn,
    output wire		layer_15_spi_clk,
    output wire		layer_15_spi_csn,
    input  wire [1:0]	layer_15_spi_miso,
    output wire		layer_15_spi_mosi,

    output wire		layer_16_hold,
    input  wire		layer_16_interruptn,
    output wire		layer_16_resn,
    output wire		layer_16_spi_clk,
    output wire		layer_16_spi_csn,
    input  wire [1:0]	layer_16_spi_miso,
    output wire		layer_16_spi_mosi,

    output wire		layer_17_hold,
    input  wire		layer_17_interruptn,
    output wire		layer_17_resn,
    output wire		layer_17_spi_clk,
    output wire		layer_17_spi_csn,
    input  wire [1:0]	layer_17_spi_miso,
    output wire		layer_17_spi_mosi,

    output wire		layer_18_hold,
    input  wire		layer_18_interruptn,
    output wire		layer_18_resn,
    output wire		layer_18_spi_clk,
    output wire		layer_18_spi_csn,
    input  wire [1:0]	layer_18_spi_miso,
    output wire		layer_18_spi_mosi,

    output wire		layer_19_hold,
    input  wire		layer_19_interruptn,
    output wire		layer_19_resn,
    output wire		layer_19_spi_clk,
    output wire		layer_19_spi_csn,
    input  wire [1:0]	layer_19_spi_miso,
    output wire		layer_19_spi_mosi,

    output wire         layers_inj,
    output wire         layers_spi_csn, // This is a merged CS for all layers
    output wire		layers_sr_in_rb,
    input  wire		layers_sr_in_sout0,
    input  wire		layers_sr_in_sout1,
    input  wire		layers_sr_in_sout2,
    output wire		layers_sr_out_ck1,
    output wire		layers_sr_out_ck2,
    output wire		layers_sr_out_ld0,
    output wire		layers_sr_out_ld1,
    output wire		layers_sr_out_ld2,
    output wire		layers_sr_out_sin,

    input  wire		spi_clk,
    input  wire		spi_csn,
    output wire		spi_miso,
    input  wire		spi_mosi,

    input  wire		uart_rx,
    output wire		uart_tx,
    output wire         uart_init_done,
    output wire         uart_got_byte,

    // Target Specific
    //---------------
    output wire         gecco_sr_ctrl_ck,
    output wire         gecco_sr_ctrl_sin,
    output wire         gecco_sr_ctrl_ld,

    // IO Control
    //-----------
    output wire io_ctrl_sample_clock_enable,
    output wire io_ctrl_timestamp_clock_enable,
    output wire io_ctrl_gecco_sample_clock_se,
    output wire io_ctrl_gecco_inj_enable
);



    // Clocking
    //-------------------
    wire clk_100; // size=1
    wire clk_100_resn; // size=1
    wire clk_uart; // size=1
    wire clk_uart_resn; // size=1
    wire clk_core; // size=1
    wire clk_core_resn; // size=1
    astep24_20l_top_clocking  clocking_reset_I (
        .sysclk_in(sysclk),
        .cold_resn_in(cold_resn),
        .io_aresn(io_aresn),
        .warm_resn_in(warm_resn),
        .clk_core(clk_core),
        .clk_core_resn(clk_core_resn),
        .clk_sample(clk_sample),
        .clk_timestamp(clk_timestamp),
        .clk_uart(clk_uart),
        .clk_uart_resn(clk_uart_resn)
    );

    // Interrupt Input Sychronisation
    //-----------
    wire [19:0] layers_interruptn = {layer_19_interruptn, layer_18_interruptn, layer_17_interruptn, layer_16_interruptn,
                                     layer_15_interruptn, layer_14_interruptn,layer_13_interruptn,layer_12_interruptn,
                                     layer_11_interruptn, layer_10_interruptn,layer_9_interruptn,layer_8_interruptn,
                                     layer_7_interruptn, layer_6_interruptn,layer_5_interruptn,layer_4_interruptn,
                                     layer_3_interruptn, layer_2_interruptn,layer_1_interruptn,layer_0_interruptn};
    wire [19:0] layers_interruptn_synced;
    genvar li;
    generate
        for (li = 0 ; li < 20 ; li++) begin
            async_input_sync #(.RESET_VALUE(1'b1),.DEBOUNCE_DELAY(2)) layer_interrupt_sync (
                .async_input(layers_interruptn[li]),
                .clk(clk_core),
                .resn(clk_core_resn),
                .sync_out(layers_interruptn_synced[li])
            );
        end
    endgenerate



    // SW interface
    //-------------
    wire [15:0] sw_if_rfg_address;
    wire [7:0] sw_if_rfg_write_value;
    wire [7:0] sw_if_rfg_read_value;
    wire sw_if_rfg_write;
    wire sw_if_rfg_write_last;
    wire sw_if_rfg_read;
    wire sw_if_rfg_read_valid;


    sw_spi_uart  sw_if (
        .clk_core(clk_core),
        .clk_core_resn(clk_core_resn),

        .clk_uart(clk_uart),
        .clk_uart_resn(clk_uart_resn),

        .rfg_address(sw_if_rfg_address),
        .rfg_read(sw_if_rfg_read),
        .rfg_read_valid(sw_if_rfg_read_valid),
        .rfg_read_value(sw_if_rfg_read_value),
        .rfg_write(sw_if_rfg_write),
        .rfg_write_last(sw_if_rfg_write_last),
        .rfg_write_value(sw_if_rfg_write_value),

        .spi_clk(spi_clk),
        .spi_csn(spi_csn),
        .spi_miso(spi_miso),
        .spi_mosi(spi_mosi),

        .uart_rx(uart_rx),
        .uart_tx(uart_tx),
        .uart_init_done(uart_init_done),
        .uart_got_byte(uart_got_byte),

        .rfg_debug_got_byte(rfg_debug_got_byte)

    );


    // Register File
    //-----------------

    wire [7:0]  injection_generator_inj_wdata;
    wire [3:0]  injection_generator_inj_waddr;

    wire [7:0]  hk_dac_mosi_fifo_m_axis_tdata;
    wire [7:0]  hk_adcdac_mosi_fifo_m_axis_tdata;
    wire [31:0] hk_adc_miso_fifo_read_size;
    wire [7:0]  hk_adc_miso_fifo_s_axis_tdata;
    wire [15:0] hk_xadc_temperature;
    wire [15:0] hk_xadc_vccint;

    wire [7:0]  layer_0_mosi_tdata;
    wire [7:0]  layer_1_mosi_tdata;
    wire [7:0]  layer_2_mosi_tdata;
    wire [7:0]  layer_3_mosi_tdata;
    wire [7:0]  layer_4_mosi_tdata;
    wire [7:0]  layer_5_mosi_tdata;
    wire [7:0]  layer_6_mosi_tdata;
    wire [7:0]  layer_7_mosi_tdata;
    wire [7:0]  layer_8_mosi_tdata;
    wire [7:0]  layer_9_mosi_tdata;
    wire [7:0]  layer_10_mosi_tdata;
    wire [7:0]  layer_11_mosi_tdata;
    wire [7:0]  layer_12_mosi_tdata;
    wire [7:0]  layer_13_mosi_tdata;
    wire [7:0]  layer_14_mosi_tdata;
    wire [7:0]  layer_15_mosi_tdata;
    wire [7:0]  layer_16_mosi_tdata;
    wire [7:0]  layer_17_mosi_tdata;
    wire [7:0]  layer_18_mosi_tdata;
    wire [7:0]  layer_19_mosi_tdata;

    wire [31:0] layer_0_mosi_write_size;
    wire [31:0] layer_1_mosi_write_size;
    wire [31:0] layer_2_mosi_write_size;
    wire [31:0] layer_3_mosi_write_size;
    wire [31:0] layer_4_mosi_write_size;
    wire [31:0] layer_5_mosi_write_size;
    wire [31:0] layer_6_mosi_write_size;
    wire [31:0] layer_7_mosi_write_size;
    wire [31:0] layer_8_mosi_write_size;
    wire [31:0] layer_9_mosi_write_size;
    wire [31:0] layer_10_mosi_write_size;
    wire [31:0] layer_11_mosi_write_size;
    wire [31:0] layer_12_mosi_write_size;
    wire [31:0] layer_13_mosi_write_size;
    wire [31:0] layer_14_mosi_write_size;
    wire [31:0] layer_15_mosi_write_size;
    wire [31:0] layer_16_mosi_write_size;
    wire [31:0] layer_17_mosi_write_size;
    wire [31:0] layer_18_mosi_write_size;
    wire [31:0] layer_19_mosi_write_size;

    wire layer_0_reset;
    wire layer_1_reset;
    wire layer_2_reset;
    wire layer_3_reset;
    wire layer_4_reset;
    wire layer_5_reset;
    wire layer_6_reset;
    wire layer_7_reset;
    wire layer_8_reset;
    wire layer_9_reset;
    wire layer_10_reset;
    wire layer_11_reset;
    wire layer_12_reset;
    wire layer_13_reset;
    wire layer_14_reset;
    wire layer_15_reset;
    wire layer_16_reset;
    wire layer_17_reset;
    wire layer_18_reset;
    wire layer_19_reset;


    assign layer_0_resn = !layer_0_reset;
    assign layer_1_resn = !layer_1_reset;
    assign layer_2_resn = !layer_2_reset;
    assign layer_3_resn = !layer_3_reset;
    assign layer_4_resn = !layer_4_reset;
    assign layer_5_resn = !layer_5_reset;
    assign layer_6_resn = !layer_6_reset;
    assign layer_7_resn = !layer_7_reset;
    assign layer_8_resn = !layer_8_reset;
    assign layer_9_resn = !layer_9_reset;
    assign layer_10_resn = !layer_10_reset;
    assign layer_11_resn = !layer_11_reset;
    assign layer_12_resn = !layer_12_reset;
    assign layer_13_resn = !layer_13_reset;
    assign layer_14_resn = !layer_14_reset;
    assign layer_15_resn = !layer_15_reset;
    assign layer_16_resn = !layer_16_reset;
    assign layer_17_resn = !layer_17_reset;
    assign layer_18_resn = !layer_18_reset;
    assign layer_19_resn = !layer_19_reset;


    wire [7:0]  layers_readout_s_axis_tdata;
    wire [31:0] layers_readout_read_size;
    wire [7:0]  layers_cfg_nodata_continue;
    wire [31:0] layers_cfg_frame_tag_counter;

    wire hk_conversion_trigger_interrupt;
    wire hk_ctrl_select_adc0;
    wire hk_ctrl_select_adc1;
    wire hk_ctrl_select_adc2;

    main_rfg  main_rfg_I (

        .clk(clk_core),
        .resn(clk_core_resn),
        .rfg_address(sw_if_rfg_address),
        .rfg_write_value(sw_if_rfg_write_value),
        .rfg_write(sw_if_rfg_write),
        .rfg_write_last(sw_if_rfg_write_last),
        .rfg_read(sw_if_rfg_read),
        .rfg_read_valid(sw_if_rfg_read_valid),
        .rfg_read_value(sw_if_rfg_read_value),

        //.io_led(rfg_io_led[7:0]),

        .hk_xadc_temperature(hk_xadc_temperature),
        .hk_xadc_temperature_write(hk_xadc_temperature_write),
        .hk_xadc_vccint(hk_xadc_vccint),
        .hk_xadc_vccint_write(hk_xadc_vccint_write),
        .hk_conversion_trigger(),
        .hk_conversion_trigger_interrupt(hk_conversion_trigger_interrupt),
        .hk_stat_conversions_counter_enable(hk_xadc_temperature_write),
        .hk_ctrl(),
        .hk_ctrl_select_adc0(hk_ctrl_select_adc0),
        .hk_ctrl_select_adc1(hk_ctrl_select_adc1),
        .hk_ctrl_select_adc2(hk_ctrl_select_adc2),
        .hk_conversion_trigger_match(),

        // ADC+DAC -> MOSI
        .hk_adcdac_mosi_fifo_m_axis_tdata(hk_adcdac_mosi_fifo_m_axis_tdata),
        .hk_adcdac_mosi_fifo_m_axis_tvalid(hk_adcdac_mosi_fifo_m_axis_tvalid),
        .hk_adcdac_mosi_fifo_m_axis_tready(hk_adcdac_mosi_fifo_m_axis_tready),
        .hk_adcdac_mosi_fifo_m_axis_tlast(hk_adcdac_mosi_fifo_m_axis_tlast),

        // ADC <- MISO
        .hk_adc_miso_fifo_s_axis_tdata(hk_adc_miso_fifo_s_axis_tdata),
        .hk_adc_miso_fifo_s_axis_tvalid(hk_adc_miso_fifo_s_axis_tvalid),
        .hk_adc_miso_fifo_s_axis_tready(hk_adc_miso_fifo_s_axis_tready),
        .hk_adc_miso_fifo_read_size(hk_adc_miso_fifo_read_size),
        .hk_adc_miso_fifo_read_size_write(1'b1),

        // SPI Clock Dividers
        .spi_layers_ckdivider_source_clk(clk_core),
        .spi_layers_ckdivider_source_resn(clk_core_resn),
        .spi_layers_ckdivider_divided_clk(spi_layers_ckdivider_divided_clk),
        .spi_layers_ckdivider_divided_resn(spi_layers_ckdivider_divided_resn),

        .spi_hk_ckdivider_source_clk(clk_core),
        .spi_hk_ckdivider_source_resn(clk_core_resn),
        .spi_hk_ckdivider_divided_clk(spi_hk_ckdivider_divided_clk),
        .spi_hk_ckdivider_divided_resn(spi_hk_ckdivider_divided_resn),

        // Layers Controls
        .layer_0_cfg_ctrl(),
        .layer_0_cfg_ctrl_disable_autoread(layer_0_cfg_ctrl_disable_autoread),
        .layer_0_cfg_ctrl_reset(layer_0_reset),
        .layer_0_cfg_ctrl_hold(layer_0_hold),
        .layer_0_cfg_ctrl_cs(layer_0_cfg_ctrl_cs),
        .layer_0_cfg_ctrl_disable_miso(layer_0_cfg_ctrl_disable_miso),

        .layer_1_cfg_ctrl(),
        .layer_1_cfg_ctrl_disable_autoread(layer_1_cfg_ctrl_disable_autoread),
        .layer_1_cfg_ctrl_reset(layer_1_reset),
        .layer_1_cfg_ctrl_hold(layer_1_hold),
        .layer_1_cfg_ctrl_cs(layer_1_cfg_ctrl_cs),
        .layer_1_cfg_ctrl_disable_miso(layer_1_cfg_ctrl_disable_miso),

        .layer_2_cfg_ctrl(),
        .layer_2_cfg_ctrl_disable_autoread(layer_2_cfg_ctrl_disable_autoread),
        .layer_2_cfg_ctrl_reset(layer_2_reset),
        .layer_2_cfg_ctrl_hold(layer_2_hold),
        .layer_2_cfg_ctrl_cs(layer_2_cfg_ctrl_cs),
        .layer_2_cfg_ctrl_disable_miso(layer_2_cfg_ctrl_disable_miso),

        .layer_3_cfg_ctrl(),
        .layer_3_cfg_ctrl_disable_autoread(layer_3_cfg_ctrl_disable_autoread),
        .layer_3_cfg_ctrl_reset(layer_3_reset),
        .layer_3_cfg_ctrl_hold(layer_3_hold),
        .layer_3_cfg_ctrl_cs(layer_3_cfg_ctrl_cs),
        .layer_3_cfg_ctrl_disable_miso(layer_3_cfg_ctrl_disable_miso),

		.layer_4_cfg_ctrl(),
        .layer_4_cfg_ctrl_disable_autoread(layer_4_cfg_ctrl_disable_autoread),
        .layer_4_cfg_ctrl_reset(layer_4_reset),
        .layer_4_cfg_ctrl_hold(layer_4_hold),
        .layer_4_cfg_ctrl_cs(layer_4_cfg_ctrl_cs),
        .layer_4_cfg_ctrl_disable_miso(layer_4_cfg_ctrl_disable_miso),

		.layer_5_cfg_ctrl(),
        .layer_5_cfg_ctrl_disable_autoread(layer_5_cfg_ctrl_disable_autoread),
        .layer_5_cfg_ctrl_reset(layer_5_reset),
        .layer_5_cfg_ctrl_hold(layer_5_hold),
        .layer_5_cfg_ctrl_cs(layer_5_cfg_ctrl_cs),
        .layer_5_cfg_ctrl_disable_miso(layer_5_cfg_ctrl_disable_miso),

		.layer_6_cfg_ctrl(),
        .layer_6_cfg_ctrl_disable_autoread(layer_6_cfg_ctrl_disable_autoread),
        .layer_6_cfg_ctrl_reset(layer_6_reset),
        .layer_6_cfg_ctrl_hold(layer_6_hold),
        .layer_6_cfg_ctrl_cs(layer_6_cfg_ctrl_cs),
        .layer_6_cfg_ctrl_disable_miso(layer_6_cfg_ctrl_disable_miso),

		.layer_7_cfg_ctrl(),
        .layer_7_cfg_ctrl_disable_autoread(layer_7_cfg_ctrl_disable_autoread),
        .layer_7_cfg_ctrl_reset(layer_7_reset),
        .layer_7_cfg_ctrl_hold(layer_7_hold),
        .layer_7_cfg_ctrl_cs(layer_7_cfg_ctrl_cs),
        .layer_7_cfg_ctrl_disable_miso(layer_7_cfg_ctrl_disable_miso),

		.layer_8_cfg_ctrl(),
        .layer_8_cfg_ctrl_disable_autoread(layer_8_cfg_ctrl_disable_autoread),
        .layer_8_cfg_ctrl_reset(layer_8_reset),
        .layer_8_cfg_ctrl_hold(layer_8_hold),
        .layer_8_cfg_ctrl_cs(layer_8_cfg_ctrl_cs),
        .layer_8_cfg_ctrl_disable_miso(layer_8_cfg_ctrl_disable_miso),

		.layer_9_cfg_ctrl(),
        .layer_9_cfg_ctrl_disable_autoread(layer_9_cfg_ctrl_disable_autoread),
        .layer_9_cfg_ctrl_reset(layer_9_reset),
        .layer_9_cfg_ctrl_hold(layer_9_hold),
        .layer_9_cfg_ctrl_cs(layer_9_cfg_ctrl_cs),
        .layer_9_cfg_ctrl_disable_miso(layer_9_cfg_ctrl_disable_miso),

		.layer_10_cfg_ctrl(),
        .layer_10_cfg_ctrl_disable_autoread(layer_10_cfg_ctrl_disable_autoread),
        .layer_10_cfg_ctrl_reset(layer_10_reset),
        .layer_10_cfg_ctrl_hold(layer_10_hold),
        .layer_10_cfg_ctrl_cs(layer_10_cfg_ctrl_cs),
        .layer_10_cfg_ctrl_disable_miso(layer_10_cfg_ctrl_disable_miso),

		.layer_11_cfg_ctrl(),
        .layer_11_cfg_ctrl_disable_autoread(layer_11_cfg_ctrl_disable_autoread),
        .layer_11_cfg_ctrl_reset(layer_11_reset),
        .layer_11_cfg_ctrl_hold(layer_11_hold),
        .layer_11_cfg_ctrl_cs(layer_11_cfg_ctrl_cs),
        .layer_11_cfg_ctrl_disable_miso(layer_11_cfg_ctrl_disable_miso),

		.layer_12_cfg_ctrl(),
        .layer_12_cfg_ctrl_disable_autoread(layer_12_cfg_ctrl_disable_autoread),
        .layer_12_cfg_ctrl_reset(layer_12_reset),
        .layer_12_cfg_ctrl_hold(layer_12_hold),
        .layer_12_cfg_ctrl_cs(layer_12_cfg_ctrl_cs),
        .layer_12_cfg_ctrl_disable_miso(layer_12_cfg_ctrl_disable_miso),

		.layer_13_cfg_ctrl(),
        .layer_13_cfg_ctrl_disable_autoread(layer_13_cfg_ctrl_disable_autoread),
        .layer_13_cfg_ctrl_reset(layer_13_reset),
        .layer_13_cfg_ctrl_hold(layer_13_hold),
        .layer_13_cfg_ctrl_cs(layer_13_cfg_ctrl_cs),
        .layer_13_cfg_ctrl_disable_miso(layer_13_cfg_ctrl_disable_miso),

		.layer_14_cfg_ctrl(),
        .layer_14_cfg_ctrl_disable_autoread(layer_14_cfg_ctrl_disable_autoread),
        .layer_14_cfg_ctrl_reset(layer_14_reset),
        .layer_14_cfg_ctrl_hold(layer_14_hold),
        .layer_14_cfg_ctrl_cs(layer_14_cfg_ctrl_cs),
        .layer_14_cfg_ctrl_disable_miso(layer_14_cfg_ctrl_disable_miso),

		.layer_15_cfg_ctrl(),
        .layer_15_cfg_ctrl_disable_autoread(layer_15_cfg_ctrl_disable_autoread),
        .layer_15_cfg_ctrl_reset(layer_15_reset),
        .layer_15_cfg_ctrl_hold(layer_15_hold),
        .layer_15_cfg_ctrl_cs(layer_15_cfg_ctrl_cs),
        .layer_15_cfg_ctrl_disable_miso(layer_15_cfg_ctrl_disable_miso),

		.layer_16_cfg_ctrl(),
        .layer_16_cfg_ctrl_disable_autoread(layer_16_cfg_ctrl_disable_autoread),
        .layer_16_cfg_ctrl_reset(layer_16_reset),
        .layer_16_cfg_ctrl_hold(layer_16_hold),
        .layer_16_cfg_ctrl_cs(layer_16_cfg_ctrl_cs),
        .layer_16_cfg_ctrl_disable_miso(layer_16_cfg_ctrl_disable_miso),

		.layer_17_cfg_ctrl(),
        .layer_17_cfg_ctrl_disable_autoread(layer_17_cfg_ctrl_disable_autoread),
        .layer_17_cfg_ctrl_reset(layer_17_reset),
        .layer_17_cfg_ctrl_hold(layer_17_hold),
        .layer_17_cfg_ctrl_cs(layer_17_cfg_ctrl_cs),
        .layer_17_cfg_ctrl_disable_miso(layer_17_cfg_ctrl_disable_miso),

		.layer_18_cfg_ctrl(),
        .layer_18_cfg_ctrl_disable_autoread(layer_18_cfg_ctrl_disable_autoread),
        .layer_18_cfg_ctrl_reset(layer_18_reset),
        .layer_18_cfg_ctrl_hold(layer_18_hold),
        .layer_18_cfg_ctrl_cs(layer_18_cfg_ctrl_cs),
        .layer_18_cfg_ctrl_disable_miso(layer_18_cfg_ctrl_disable_miso),

		.layer_19_cfg_ctrl(),
        .layer_19_cfg_ctrl_disable_autoread(layer_19_cfg_ctrl_disable_autoread),
        .layer_19_cfg_ctrl_reset(layer_19_reset),
        .layer_19_cfg_ctrl_hold(layer_19_hold),
        .layer_19_cfg_ctrl_cs(layer_19_cfg_ctrl_cs),
        .layer_19_cfg_ctrl_disable_miso(layer_19_cfg_ctrl_disable_miso),

        .layer_0_status(),
        .layer_0_status_interruptn(layers_interruptn_synced[0]),
        .layer_0_status_frame_decoding(layer_0_status_frame_decoding),

        .layer_1_status(),
        .layer_1_status_interruptn(layers_interruptn_synced[1]),
        .layer_1_status_frame_decoding(layer_1_status_frame_decoding),

        .layer_2_status(),
        .layer_2_status_interruptn(layers_interruptn_synced[2]),
        .layer_2_status_frame_decoding(layer_2_status_frame_decoding),

        .layer_3_status(),
        .layer_3_status_interruptn(layers_interruptn_synced[3]),
        .layer_3_status_frame_decoding(layer_3_status_frame_decoding),

        .layer_4_status(),
        .layer_4_status_interruptn(layers_interruptn_synced[4]),
        .layer_4_status_frame_decoding(layer_4_status_frame_decoding),

        .layer_5_status(),
        .layer_5_status_interruptn(layers_interruptn_synced[5]),
        .layer_5_status_frame_decoding(layer_5_status_frame_decoding),

        .layer_6_status(),
        .layer_6_status_interruptn(layers_interruptn_synced[6]),
        .layer_6_status_frame_decoding(layer_6_status_frame_decoding),

        .layer_7_status(),
        .layer_7_status_interruptn(layers_interruptn_synced[7]),
        .layer_7_status_frame_decoding(layer_7_status_frame_decoding),

        .layer_8_status(),
        .layer_8_status_interruptn(layers_interruptn_synced[8]),
        .layer_8_status_frame_decoding(layer_8_status_frame_decoding),

        .layer_9_status(),
        .layer_9_status_interruptn(layers_interruptn_synced[9]),
        .layer_9_status_frame_decoding(layer_9_status_frame_decoding),

        .layer_10_status(),
        .layer_10_status_interruptn(layers_interruptn_synced[10]),
        .layer_10_status_frame_decoding(layer_10_status_frame_decoding),

        .layer_11_status(),
        .layer_11_status_interruptn(layers_interruptn_synced[11]),
        .layer_11_status_frame_decoding(layer_11_status_frame_decoding),

        .layer_12_status(),
        .layer_12_status_interruptn(layers_interruptn_synced[12]),
        .layer_12_status_frame_decoding(layer_12_status_frame_decoding),

        .layer_13_status(),
        .layer_13_status_interruptn(layers_interruptn_synced[13]),
        .layer_13_status_frame_decoding(layer_13_status_frame_decoding),

        .layer_14_status(),
        .layer_14_status_interruptn(layers_interruptn_synced[14]),
        .layer_14_status_frame_decoding(layer_14_status_frame_decoding),

        .layer_15_status(),
        .layer_15_status_interruptn(layers_interruptn_synced[15]),
        .layer_15_status_frame_decoding(layer_15_status_frame_decoding),

        .layer_16_status(),
        .layer_16_status_interruptn(layers_interruptn_synced[16]),
        .layer_16_status_frame_decoding(layer_16_status_frame_decoding),

        .layer_17_status(),
        .layer_17_status_interruptn(layers_interruptn_synced[17]),
        .layer_17_status_frame_decoding(layer_17_status_frame_decoding),

        .layer_18_status(),
        .layer_18_status_interruptn(layers_interruptn_synced[18]),
        .layer_18_status_frame_decoding(layer_18_status_frame_decoding),

        .layer_19_status(),
        .layer_19_status_interruptn(layers_interruptn_synced[19]),
        .layer_19_status_frame_decoding(layer_19_status_frame_decoding),

        .layer_0_stat_frame_counter_enable(layer_0_stat_frame_counter_enable),
        .layer_1_stat_frame_counter_enable(layer_1_stat_frame_counter_enable),
        .layer_2_stat_frame_counter_enable(layer_2_stat_frame_counter_enable),
        .layer_3_stat_frame_counter_enable(layer_3_stat_frame_counter_enable),
        .layer_4_stat_frame_counter_enable(layer_4_stat_frame_counter_enable),
        .layer_5_stat_frame_counter_enable(layer_5_stat_frame_counter_enable),
        .layer_6_stat_frame_counter_enable(layer_6_stat_frame_counter_enable),
        .layer_7_stat_frame_counter_enable(layer_7_stat_frame_counter_enable),
        .layer_8_stat_frame_counter_enable(layer_8_stat_frame_counter_enable),
        .layer_9_stat_frame_counter_enable(layer_9_stat_frame_counter_enable),
        .layer_10_stat_frame_counter_enable(layer_10_stat_frame_counter_enable),
        .layer_11_stat_frame_counter_enable(layer_11_stat_frame_counter_enable),
        .layer_12_stat_frame_counter_enable(layer_12_stat_frame_counter_enable),
        .layer_13_stat_frame_counter_enable(layer_13_stat_frame_counter_enable),
        .layer_14_stat_frame_counter_enable(layer_14_stat_frame_counter_enable),
        .layer_15_stat_frame_counter_enable(layer_15_stat_frame_counter_enable),
        .layer_16_stat_frame_counter_enable(layer_16_stat_frame_counter_enable),
        .layer_17_stat_frame_counter_enable(layer_17_stat_frame_counter_enable),
        .layer_18_stat_frame_counter_enable(layer_18_stat_frame_counter_enable),
        .layer_19_stat_frame_counter_enable(layer_19_stat_frame_counter_enable),

        .layer_0_stat_idle_counter_enable(layer_0_stat_idle_counter_enable),
        .layer_1_stat_idle_counter_enable(layer_1_stat_idle_counter_enable),
        .layer_2_stat_idle_counter_enable(layer_2_stat_idle_counter_enable),
        .layer_3_stat_idle_counter_enable(layer_3_stat_idle_counter_enable),
        .layer_4_stat_idle_counter_enable(layer_4_stat_idle_counter_enable),
        .layer_5_stat_idle_counter_enable(layer_5_stat_idle_counter_enable),
        .layer_6_stat_idle_counter_enable(layer_6_stat_idle_counter_enable),
        .layer_7_stat_idle_counter_enable(layer_7_stat_idle_counter_enable),
        .layer_8_stat_idle_counter_enable(layer_8_stat_idle_counter_enable),
        .layer_9_stat_idle_counter_enable(layer_9_stat_idle_counter_enable),
        .layer_10_stat_idle_counter_enable(layer_10_stat_idle_counter_enable),
        .layer_11_stat_idle_counter_enable(layer_11_stat_idle_counter_enable),
        .layer_12_stat_idle_counter_enable(layer_12_stat_idle_counter_enable),
        .layer_13_stat_idle_counter_enable(layer_13_stat_idle_counter_enable),
        .layer_14_stat_idle_counter_enable(layer_14_stat_idle_counter_enable),
        .layer_15_stat_idle_counter_enable(layer_15_stat_idle_counter_enable),
        .layer_16_stat_idle_counter_enable(layer_16_stat_idle_counter_enable),
        .layer_17_stat_idle_counter_enable(layer_17_stat_idle_counter_enable),
        .layer_18_stat_idle_counter_enable(layer_18_stat_idle_counter_enable),
        .layer_19_stat_idle_counter_enable(layer_19_stat_idle_counter_enable),

        .layer_0_mosi_m_axis_tdata(layer_0_mosi_tdata),
        .layer_0_mosi_m_axis_tvalid(layer_0_mosi_tvalid),
        .layer_0_mosi_m_axis_tready(layer_0_mosi_tready),
        .layer_0_mosi_m_axis_tlast(layer_0_mosi_tlast),
        .layer_0_mosi_write_size(layer_0_mosi_write_size),
        .layer_0_mosi_write_size_write(1'b1),

        .layer_1_mosi_m_axis_tdata(layer_1_mosi_tdata),
        .layer_1_mosi_m_axis_tvalid(layer_1_mosi_tvalid),
        .layer_1_mosi_m_axis_tready(layer_1_mosi_tready),
        .layer_1_mosi_m_axis_tlast(layer_1_mosi_tlast),
        .layer_1_mosi_write_size(layer_1_mosi_write_size),
        .layer_1_mosi_write_size_write(1'b1),

        .layer_2_mosi_m_axis_tdata(layer_2_mosi_tdata),
        .layer_2_mosi_m_axis_tvalid(layer_2_mosi_tvalid),
        .layer_2_mosi_m_axis_tready(layer_2_mosi_tready),
        .layer_2_mosi_m_axis_tlast(layer_2_mosi_tlast),
        .layer_2_mosi_write_size(layer_2_mosi_write_size),
        .layer_2_mosi_write_size_write(1'b1),

        .layer_3_mosi_m_axis_tdata(layer_3_mosi_tdata),
        .layer_3_mosi_m_axis_tvalid(layer_3_mosi_tvalid),
        .layer_3_mosi_m_axis_tready(layer_3_mosi_tready),
        .layer_3_mosi_m_axis_tlast(layer_3_mosi_tlast),
        .layer_3_mosi_write_size(layer_3_mosi_write_size),
        .layer_3_mosi_write_size_write(1'b1),

        .layer_4_mosi_m_axis_tdata(layer_4_mosi_tdata),
        .layer_4_mosi_m_axis_tvalid(layer_4_mosi_tvalid),
        .layer_4_mosi_m_axis_tready(layer_4_mosi_tready),
        .layer_4_mosi_m_axis_tlast(layer_4_mosi_tlast),
        .layer_4_mosi_write_size(layer_4_mosi_write_size),
        .layer_4_mosi_write_size_write(1'b1),

        .layer_5_mosi_m_axis_tdata(layer_5_mosi_tdata),
        .layer_5_mosi_m_axis_tvalid(layer_5_mosi_tvalid),
        .layer_5_mosi_m_axis_tready(layer_5_mosi_tready),
        .layer_5_mosi_m_axis_tlast(layer_5_mosi_tlast),
        .layer_5_mosi_write_size(layer_5_mosi_write_size),
        .layer_5_mosi_write_size_write(1'b1),

        .layer_6_mosi_m_axis_tdata(layer_6_mosi_tdata),
        .layer_6_mosi_m_axis_tvalid(layer_6_mosi_tvalid),
        .layer_6_mosi_m_axis_tready(layer_6_mosi_tready),
        .layer_6_mosi_m_axis_tlast(layer_6_mosi_tlast),
        .layer_6_mosi_write_size(layer_6_mosi_write_size),
        .layer_6_mosi_write_size_write(1'b1),

        .layer_7_mosi_m_axis_tdata(layer_7_mosi_tdata),
        .layer_7_mosi_m_axis_tvalid(layer_7_mosi_tvalid),
        .layer_7_mosi_m_axis_tready(layer_7_mosi_tready),
        .layer_7_mosi_m_axis_tlast(layer_7_mosi_tlast),
        .layer_7_mosi_write_size(layer_7_mosi_write_size),
        .layer_7_mosi_write_size_write(1'b1),

        .layer_8_mosi_m_axis_tdata(layer_8_mosi_tdata),
        .layer_8_mosi_m_axis_tvalid(layer_8_mosi_tvalid),
        .layer_8_mosi_m_axis_tready(layer_8_mosi_tready),
        .layer_8_mosi_m_axis_tlast(layer_8_mosi_tlast),
        .layer_8_mosi_write_size(layer_8_mosi_write_size),
        .layer_8_mosi_write_size_write(1'b1),

        .layer_9_mosi_m_axis_tdata(layer_9_mosi_tdata),
        .layer_9_mosi_m_axis_tvalid(layer_9_mosi_tvalid),
        .layer_9_mosi_m_axis_tready(layer_9_mosi_tready),
        .layer_9_mosi_m_axis_tlast(layer_9_mosi_tlast),
        .layer_9_mosi_write_size(layer_9_mosi_write_size),
        .layer_9_mosi_write_size_write(1'b1),

        .layer_10_mosi_m_axis_tdata(layer_10_mosi_tdata),
        .layer_10_mosi_m_axis_tvalid(layer_10_mosi_tvalid),
        .layer_10_mosi_m_axis_tready(layer_10_mosi_tready),
        .layer_10_mosi_m_axis_tlast(layer_10_mosi_tlast),
        .layer_10_mosi_write_size(layer_10_mosi_write_size),
        .layer_10_mosi_write_size_write(1'b1),

        .layer_11_mosi_m_axis_tdata(layer_11_mosi_tdata),
        .layer_11_mosi_m_axis_tvalid(layer_11_mosi_tvalid),
        .layer_11_mosi_m_axis_tready(layer_11_mosi_tready),
        .layer_11_mosi_m_axis_tlast(layer_11_mosi_tlast),
        .layer_11_mosi_write_size(layer_11_mosi_write_size),
        .layer_11_mosi_write_size_write(1'b1),

        .layer_12_mosi_m_axis_tdata(layer_12_mosi_tdata),
        .layer_12_mosi_m_axis_tvalid(layer_12_mosi_tvalid),
        .layer_12_mosi_m_axis_tready(layer_12_mosi_tready),
        .layer_12_mosi_m_axis_tlast(layer_12_mosi_tlast),
        .layer_12_mosi_write_size(layer_12_mosi_write_size),
        .layer_12_mosi_write_size_write(1'b1),

        .layer_13_mosi_m_axis_tdata(layer_13_mosi_tdata),
        .layer_13_mosi_m_axis_tvalid(layer_13_mosi_tvalid),
        .layer_13_mosi_m_axis_tready(layer_13_mosi_tready),
        .layer_13_mosi_m_axis_tlast(layer_13_mosi_tlast),
        .layer_13_mosi_write_size(layer_13_mosi_write_size),
        .layer_13_mosi_write_size_write(1'b1),

        .layer_14_mosi_m_axis_tdata(layer_14_mosi_tdata),
        .layer_14_mosi_m_axis_tvalid(layer_14_mosi_tvalid),
        .layer_14_mosi_m_axis_tready(layer_14_mosi_tready),
        .layer_14_mosi_m_axis_tlast(layer_14_mosi_tlast),
        .layer_14_mosi_write_size(layer_14_mosi_write_size),
        .layer_14_mosi_write_size_write(1'b1),

        .layer_15_mosi_m_axis_tdata(layer_15_mosi_tdata),
        .layer_15_mosi_m_axis_tvalid(layer_15_mosi_tvalid),
        .layer_15_mosi_m_axis_tready(layer_15_mosi_tready),
        .layer_15_mosi_m_axis_tlast(layer_15_mosi_tlast),
        .layer_15_mosi_write_size(layer_15_mosi_write_size),
        .layer_15_mosi_write_size_write(1'b1),

        .layer_16_mosi_m_axis_tdata(layer_16_mosi_tdata),
        .layer_16_mosi_m_axis_tvalid(layer_16_mosi_tvalid),
        .layer_16_mosi_m_axis_tready(layer_16_mosi_tready),
        .layer_16_mosi_m_axis_tlast(layer_16_mosi_tlast),
        .layer_16_mosi_write_size(layer_16_mosi_write_size),
        .layer_16_mosi_write_size_write(1'b1),

        .layer_17_mosi_m_axis_tdata(layer_17_mosi_tdata),
        .layer_17_mosi_m_axis_tvalid(layer_17_mosi_tvalid),
        .layer_17_mosi_m_axis_tready(layer_17_mosi_tready),
        .layer_17_mosi_m_axis_tlast(layer_17_mosi_tlast),
        .layer_17_mosi_write_size(layer_17_mosi_write_size),
        .layer_17_mosi_write_size_write(1'b1),

        .layer_18_mosi_m_axis_tdata(layer_18_mosi_tdata),
        .layer_18_mosi_m_axis_tvalid(layer_18_mosi_tvalid),
        .layer_18_mosi_m_axis_tready(layer_18_mosi_tready),
        .layer_18_mosi_m_axis_tlast(layer_18_mosi_tlast),
        .layer_18_mosi_write_size(layer_18_mosi_write_size),
        .layer_18_mosi_write_size_write(1'b1),

        .layer_19_mosi_m_axis_tdata(layer_19_mosi_tdata),
        .layer_19_mosi_m_axis_tvalid(layer_19_mosi_tvalid),
        .layer_19_mosi_m_axis_tready(layer_19_mosi_tready),
        .layer_19_mosi_m_axis_tlast(layer_19_mosi_tlast),
        .layer_19_mosi_write_size(layer_19_mosi_write_size),
        .layer_19_mosi_write_size_write(1'b1),

        .layers_cfg_frame_tag_counter_ctrl(),
        .layers_cfg_frame_tag_counter_ctrl_force_count(layers_cfg_frame_tag_counter_ctrl_force_count),
        .layers_cfg_frame_tag_counter_ctrl_enable(layers_cfg_frame_tag_counter_ctrl_enable),

        .layers_cfg_frame_tag_counter_trigger(),
        .layers_cfg_frame_tag_counter_trigger_interrupt(layers_cfg_frame_tag_counter_trigger_interrupt),
        .layers_cfg_frame_tag_counter_trigger_enable(layers_cfg_frame_tag_counter_ctrl_enable),
        .layers_cfg_frame_tag_counter_trigger_match(),

        .layers_cfg_frame_tag_counter(layers_cfg_frame_tag_counter),
        .layers_cfg_frame_tag_counter_enable(layers_cfg_frame_tag_counter_ctrl_enable && (layers_cfg_frame_tag_counter_trigger_interrupt || layers_cfg_frame_tag_counter_ctrl_force_count)),

        .layers_cfg_nodata_continue(layers_cfg_nodata_continue),

        .layers_sr_out(),
        .layers_sr_out_ck1(layers_sr_out_ck1),
        .layers_sr_out_ck2(layers_sr_out_ck2),
        .layers_sr_out_sin(layers_sr_out_sin),
        .layers_sr_out_ld0(layers_sr_out_ld0),
        .layers_sr_out_ld1(layers_sr_out_ld1),
        .layers_sr_out_ld2(layers_sr_out_ld2),

        .layers_inj_ctrl(),
        .layers_inj_ctrl_reset              (injection_generator_inj_ctrl_reset),
        .layers_inj_ctrl_suspend            (injection_generator_inj_ctrl_suspend),
        .layers_inj_ctrl_synced             (injection_generator_inj_ctrl_synced),
        .layers_inj_ctrl_trigger            (injection_generator_inj_ctrl_trigger),
        .layers_inj_ctrl_write              (injection_generator_inj_ctrl_write),
        .layers_inj_ctrl_done               (injection_generator_inj_ctrl_done),
        .layers_inj_ctrl_running            (injection_generator_inj_ctrl_running),

        .layers_inj_waddr                   (injection_generator_inj_waddr),
        .layers_inj_wdata                   (injection_generator_inj_wdata),

        .layers_sr_in(),
        .layers_sr_in_rb(layers_sr_in_rb),
        .layers_sr_in_sout0(layers_sr_in_sout0),
        .layers_sr_in_sout1(layers_sr_in_sout1),
        .layers_sr_in_sout2(layers_sr_in_sout2),

        .layers_readout_s_axis_tdata(layers_readout_s_axis_tdata),
        .layers_readout_s_axis_tvalid(layers_readout_s_axis_tvalid),
        .layers_readout_s_axis_tready(layers_readout_s_axis_tready),
        .layers_readout_read_size(layers_readout_read_size),
        .layers_readout_read_size_write(1'b1),

        // Target Specific Registers
        .gecco_sr_ctrl(),
        .gecco_sr_ctrl_ck(gecco_sr_ctrl_ck),
        .gecco_sr_ctrl_sin(gecco_sr_ctrl_sin),
        .gecco_sr_ctrl_ld(gecco_sr_ctrl_ld),

        // I/O Control like clocks
        .io_ctrl(),
        .io_ctrl_sample_clock_enable(io_ctrl_sample_clock_enable),
        .io_ctrl_timestamp_clock_enable(io_ctrl_timestamp_clock_enable),
        .io_ctrl_gecco_sample_clock_se(io_ctrl_gecco_sample_clock_se),
        .io_ctrl_gecco_inj_enable(io_ctrl_gecco_inj_enable)
  );




    // Layers Readout Module
    // - Contains Each Layer Interface with Protocol management, and the Switched buffer
    //-------------------------------
    layers_readout_switched #(.LAYER_COUNT(20)) switched_readout(
        .clk_core(clk_core),
        .clk_core_resn(clk_core_resn),
        .clk_io(spi_layers_ckdivider_divided_clk),
        .clk_io_resn(spi_layers_ckdivider_divided_resn),

        // Layers
        .layers_interruptn({
            layers_interruptn_synced[19],
            layers_interruptn_synced[18],
            layers_interruptn_synced[17],
            layers_interruptn_synced[16],
            layers_interruptn_synced[15],
            layers_interruptn_synced[14],
            layers_interruptn_synced[13],
            layers_interruptn_synced[12],
            layers_interruptn_synced[11],
            layers_interruptn_synced[10],
            layers_interruptn_synced[9],
            layers_interruptn_synced[8],
            layers_interruptn_synced[7],
            layers_interruptn_synced[6],
            layers_interruptn_synced[5],
            layers_interruptn_synced[4],
            layers_interruptn_synced[3],
            layers_interruptn_synced[2],
            layers_interruptn_synced[1],
            layers_interruptn_synced[0]}),
        .layers_spi_clk({
            layer_19_spi_clk,
            layer_18_spi_clk,
            layer_17_spi_clk,
            layer_16_spi_clk,
            layer_15_spi_clk,
            layer_14_spi_clk,
            layer_13_spi_clk,
            layer_12_spi_clk,
            layer_11_spi_clk,
            layer_10_spi_clk,
            layer_9_spi_clk,
            layer_8_spi_clk,
            layer_7_spi_clk,
            layer_6_spi_clk,
            layer_5_spi_clk,
            layer_4_spi_clk,
            layer_3_spi_clk,
            layer_2_spi_clk,
            layer_1_spi_clk,
            layer_0_spi_clk}),
        .layers_spi_mosi({
            layer_19_spi_mosi,
            layer_18_spi_mosi,
            layer_17_spi_mosi,
            layer_16_spi_mosi,
            layer_15_spi_mosi,
            layer_14_spi_mosi,
            layer_13_spi_mosi,
            layer_12_spi_mosi,
            layer_11_spi_mosi,
            layer_10_spi_mosi,
            layer_9_spi_mosi,
            layer_8_spi_mosi,
            layer_7_spi_mosi,
            layer_6_spi_mosi,
            layer_5_spi_mosi,
            layer_4_spi_mosi,
            layer_3_spi_mosi,
            layer_2_spi_mosi,
            layer_1_spi_mosi,
            layer_0_spi_mosi}),
        .layers_spi_miso({
            layer_19_spi_miso,
            layer_18_spi_miso,
            layer_17_spi_miso,
            layer_16_spi_miso,
            layer_15_spi_miso,
            layer_14_spi_miso,
            layer_13_spi_miso,
            layer_12_spi_miso,
            layer_11_spi_miso,
            layer_10_spi_miso,
            layer_9_spi_miso,
            layer_8_spi_miso,
            layer_7_spi_miso,
            layer_6_spi_miso,
            layer_5_spi_miso,
            layer_4_spi_miso,
            layer_3_spi_miso,
            layer_2_spi_miso,
            layer_1_spi_miso,
            layer_0_spi_miso}),
        .layers_spi_csn(),

        // MOSI
        //-----------
        .layers_mosi_s_axis_tdata({
            layer_19_mosi_tdata,
            layer_18_mosi_tdata,
            layer_17_mosi_tdata,
            layer_16_mosi_tdata,
            layer_15_mosi_tdata,
            layer_14_mosi_tdata,
            layer_13_mosi_tdata,
            layer_12_mosi_tdata,
            layer_11_mosi_tdata,
            layer_10_mosi_tdata,
            layer_9_mosi_tdata,
            layer_8_mosi_tdata,
            layer_7_mosi_tdata,
            layer_6_mosi_tdata,
            layer_5_mosi_tdata,
            layer_4_mosi_tdata,
            layer_3_mosi_tdata,
            layer_2_mosi_tdata,
            layer_1_mosi_tdata,
            layer_0_mosi_tdata}),
        .layers_mosi_s_axis_tlast({
            layer_19_mosi_tlast,
            layer_18_mosi_tlast,
            layer_17_mosi_tlast,
            layer_16_mosi_tlast,
            layer_15_mosi_tlast,
            layer_14_mosi_tlast,
            layer_13_mosi_tlast,
            layer_12_mosi_tlast,
            layer_11_mosi_tlast,
            layer_10_mosi_tlast,
            layer_9_mosi_tlast,
            layer_8_mosi_tlast,
            layer_7_mosi_tlast,
            layer_6_mosi_tlast,
            layer_5_mosi_tlast,
            layer_4_mosi_tlast,
            layer_3_mosi_tlast,
            layer_2_mosi_tlast,
            layer_1_mosi_tlast,
            layer_0_mosi_tlast}),
        .layers_mosi_s_axis_tready({
            layer_19_mosi_tready,
            layer_18_mosi_tready,
            layer_17_mosi_tready,
            layer_16_mosi_tready,
            layer_15_mosi_tready,
            layer_14_mosi_tready,
            layer_13_mosi_tready,
            layer_12_mosi_tready,
            layer_11_mosi_tready,
            layer_10_mosi_tready,
            layer_9_mosi_tready,
            layer_8_mosi_tready,
            layer_7_mosi_tready,
            layer_6_mosi_tready,
            layer_5_mosi_tready,
            layer_4_mosi_tready,
            layer_3_mosi_tready,
            layer_2_mosi_tready,
            layer_1_mosi_tready,
            layer_0_mosi_tready}),
        .layers_mosi_s_axis_tvalid({
            layer_19_mosi_tvalid,
            layer_18_mosi_tvalid,
            layer_17_mosi_tvalid,
            layer_16_mosi_tvalid,
            layer_15_mosi_tvalid,
            layer_14_mosi_tvalid,
            layer_13_mosi_tvalid,
            layer_12_mosi_tvalid,
            layer_11_mosi_tvalid,
            layer_10_mosi_tvalid,
            layer_9_mosi_tvalid,
            layer_8_mosi_tvalid,
            layer_7_mosi_tvalid,
            layer_6_mosi_tvalid,
            layer_5_mosi_tvalid,
            layer_4_mosi_tvalid,
            layer_3_mosi_tvalid,
            layer_2_mosi_tvalid,
            layer_1_mosi_tvalid,
            layer_0_mosi_tvalid}),
        .layers_mosi_write_size({
            layer_19_mosi_write_size,
            layer_18_mosi_write_size,
            layer_17_mosi_write_size,
            layer_16_mosi_write_size,
            layer_15_mosi_write_size,
            layer_14_mosi_write_size,
            layer_13_mosi_write_size,
            layer_12_mosi_write_size,
            layer_11_mosi_write_size,
            layer_10_mosi_write_size,
            layer_9_mosi_write_size,
            layer_8_mosi_write_size,
            layer_7_mosi_write_size,
            layer_6_mosi_write_size,
            layer_5_mosi_write_size,
            layer_4_mosi_write_size,
            layer_3_mosi_write_size,
            layer_2_mosi_write_size,
            layer_1_mosi_write_size,
            layer_0_mosi_write_size
        }),

        // MISO readout
        //-------------------
        .readout_frames_data_count(layers_readout_read_size),
        .readout_frames_m_axis_tdata(layers_readout_s_axis_tdata),
        .readout_frames_m_axis_tready(layers_readout_s_axis_tready),
        .readout_frames_m_axis_tvalid(layers_readout_s_axis_tvalid),

        // Configurations
        //---------------------
        .config_disable_autoread({
            layer_2_cfg_ctrl_disable_autoread,
            layer_1_cfg_ctrl_disable_autoread,
            layer_0_cfg_ctrl_disable_autoread
        }),
        .config_frame_tag_counter(layers_cfg_frame_tag_counter),
        .config_nodata_continue(layers_cfg_nodata_continue),
        .config_layers_reset({
            layer_18_reset,
            layer_17_reset,
            layer_16_reset,
            layer_15_reset,
            layer_14_reset,
            layer_13_reset,
            layer_12_reset,
            layer_11_reset,
            layer_10_reset,
            layer_9_reset,
            layer_8_reset,
            layer_7_reset,
            layer_6_reset,
            layer_5_reset,
            layer_4_reset,
            layer_3_reset,
            layer_2_reset,
            layer_1_reset,
            layer_0_reset
        }),
        .config_layers_disable_miso({
            layer_18_cfg_ctrl_disable_miso,
            layer_17_cfg_ctrl_disable_miso,
            layer_16_cfg_ctrl_disable_miso,
            layer_15_cfg_ctrl_disable_miso,
            layer_14_cfg_ctrl_disable_miso,
            layer_13_cfg_ctrl_disable_miso,
            layer_12_cfg_ctrl_disable_miso,
            layer_11_cfg_ctrl_disable_miso,
            layer_10_cfg_ctrl_disable_miso,
            layer_9_cfg_ctrl_disable_miso,
            layer_8_cfg_ctrl_disable_miso,
            layer_7_cfg_ctrl_disable_miso,
            layer_6_cfg_ctrl_disable_miso,
            layer_5_cfg_ctrl_disable_miso,
            layer_4_cfg_ctrl_disable_miso,
            layer_3_cfg_ctrl_disable_miso,
            layer_2_cfg_ctrl_disable_miso,
            layer_1_cfg_ctrl_disable_miso,
            layer_0_cfg_ctrl_disable_miso
        }),

        // Statistics
        //----------------------
        .layers_status_frame_decoding({
            layer_19_status_frame_decoding,
            layer_18_status_frame_decoding,
            layer_17_status_frame_decoding,
            layer_16_status_frame_decoding,
            layer_15_status_frame_decoding,
            layer_14_status_frame_decoding,
            layer_13_status_frame_decoding,
            layer_12_status_frame_decoding,
            layer_11_status_frame_decoding,
            layer_10_status_frame_decoding,
            layer_9_status_frame_decoding,
            layer_8_status_frame_decoding,
            layer_7_status_frame_decoding,
            layer_6_status_frame_decoding,
            layer_5_status_frame_decoding,
            layer_4_status_frame_decoding,
            layer_3_status_frame_decoding,
            layer_2_status_frame_decoding,
            layer_1_status_frame_decoding,
            layer_0_status_frame_decoding
        }),
        .layers_stat_count_frame({
            layer_9_stat_frame_counter_enable,
            layer_8_stat_frame_counter_enable,
            layer_7_stat_frame_counter_enable,
            layer_6_stat_frame_counter_enable,
            layer_5_stat_frame_counter_enable,
            layer_4_stat_frame_counter_enable,
            layer_3_stat_frame_counter_enable,
            layer_2_stat_frame_counter_enable,
            layer_1_stat_frame_counter_enable,
            layer_0_stat_frame_counter_enable}),
        .layers_stat_count_idle({
            layer_2_stat_idle_counter_enable,
            layer_1_stat_idle_counter_enable,
            layer_0_stat_idle_counter_enable})
    );

    // Injection Generator
    //-------------------
    sync_async_patgen  injection_generator (
        .clk                (clk_core),
        .rst               (injection_generator_inj_ctrl_reset),

        .out                (layers_inj),

        .rfg_write          (injection_generator_inj_ctrl_write),
        .rfg_write_address  (injection_generator_inj_waddr),
        .rfg_write_data     (injection_generator_inj_wdata),

        .done               (injection_generator_inj_ctrl_done),
        .running            (injection_generator_inj_ctrl_running),
        .suspend            (injection_generator_inj_ctrl_suspend),
        .synced             (injection_generator_inj_ctrl_synced),
        .syncrst            (injection_generator_inj_ctrl_trigger)
    );



    // Housekeeping
    //--------------------
    housekeeping_main  housekeeping(
        .clk_core(clk_core),
        .clk_core_resn(clk_core_resn),

        .clk_spi(spi_hk_ckdivider_divided_clk),
        .clk_spi_resn(spi_hk_ckdivider_divided_resn),

        .select_adc({hk_ctrl_select_adc2 , hk_ctrl_select_adc1 , hk_ctrl_select_adc0}),

        .ext_adc_miso_m_axis_tdata(hk_adc_miso_fifo_s_axis_tdata),
        .ext_adc_miso_m_axis_tready(hk_adc_miso_fifo_s_axis_tready),
        .ext_adc_miso_m_axis_tvalid(hk_adc_miso_fifo_s_axis_tvalid),
        .ext_adc_miso_read_size(hk_adc_miso_fifo_read_size),

        .ext_adcdac_mosi_s_axis_tdata(hk_adcdac_mosi_fifo_m_axis_tdata),
        .ext_adcdac_mosi_s_axis_tlast(hk_adcdac_mosi_fifo_m_axis_tlast),
        .ext_adcdac_mosi_s_axis_tready(hk_adcdac_mosi_fifo_m_axis_tready),
        .ext_adcdac_mosi_s_axis_tvalid(hk_adcdac_mosi_fifo_m_axis_tvalid),

        .ext_spi_clk(ext_spi_clk_internal),
        .ext_spi_csn(ext_spi_csn_internal),
        .ext_spi_miso(ext_adc_spi_miso),
        .ext_spi_mosi(ext_spi_mosi)


    );

    // SPI IO
    //-----------------

    //-- Shared CSN for Layers
    //---------------

    // First layers CSN are set by the control register
    // When Autoread is on, always set CSN to 0 - otherwise the CS control bit sets it
    assign layer_0_spi_csn = !(layer_0_cfg_ctrl_cs || !layer_0_cfg_ctrl_disable_autoread) ;
    assign layer_1_spi_csn = !(layer_1_cfg_ctrl_cs || !layer_1_cfg_ctrl_disable_autoread) ;
    assign layer_2_spi_csn = !(layer_2_cfg_ctrl_cs || !layer_2_cfg_ctrl_disable_autoread) ;
    assign layers_spi_csn = layer_0_spi_csn & layer_1_spi_csn & layer_2_spi_csn;

    //-- Housekeeping
    //--------------

    //-- MOSI and CLK is shared
    //-- CSN is selected based on RFG control

    assign ext_spi_clk = ext_spi_clk_internal;
    assign ext_adc_spi_csn[2] = !hk_ctrl_select_adc2;
    assign ext_adc_spi_csn[1] = !hk_ctrl_select_adc1;
    assign ext_adc_spi_csn[0] = !hk_ctrl_select_adc0;


    `ifdef SIMULATION
    GSR_CORE GSR_INST ( .GSR_N(1'b1), .CLK(1'b0));
    `endif

endmodule
